name: Deploy Sipinter

on:
  push:
    branches:
      - STAGING
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            if [ "${{ github.ref_name }}" = "STAGING" ]; then
              echo "Deploying STAGING..."
              cd /var/www/sipinter-dev/
              git pull origin STAGING

            elif [ "${{ github.ref_name }}" = "master" ]; then
              echo "Deploying MASTER..."
              cd /var/www/sipinter-lpmaarifnu-pbnu/
              git pull origin master

            else
              echo "Unknown branch: ${{ github.ref_name }}"
              exit 1
            fi
```
